version: '3'
services:
  mariadb:
    build: ./requirements/mariadb 
    environment:
      - SQL_DATABASE=${SQL_DATABASE}
      - SQL_USER=${SQL_USER}
      - SQL_PASSWORD=${SQL_PASSWORD}
      - SQL_ROOT_PASSWORD=${SQL_ROOT_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - inception
    healthcheck:
      test: mysqladmin ping --host=localhost -p${SQL_ROOT_PASSWORD}
      interval: 5s
      timeout: 1s
      retries: 20
      start_period: 5s
    restart: unless-stopped

  wordpress:
    build: ./requirements/wordpress
    volumes:
      - wordpress_data:/var/www/html
    restart: unless-stopped
    env_file: .env
    depends_on:
      mariadb:
        condition: service_healthy 
    networks:
      - inception

  nginx:
    build: ./requirements/nginx
    volumes:
      - wordpress_data:/var/www/html
    depends_on:
      - wordpress
    ports:
      - "443:443"
    networks:
      - inception
    restart: unless-stopped
    env_file: .env
    healthcheck:
      test: 'curl -kfsSL https://localhost:443/status'
      interval: 5s
      timeout: 1s
      retries: 10
      start_period: 5s


volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/rz/data/mariadb'
  wordpress_data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/rz/data/wordpress'

networks:
  inception:
    driver: bridge
